global:
  resolve_timeout: 1m

route:
  receiver: retraining-webhook
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: retraining-webhook
    webhook_configs:
      - url: http://host.docker.internal:9001/retrain
        send_resolved: true
